/**
 * Curated gazetteer of high-frequency OSINT entities.
 * Used by entityExtractor.js for non-English text and as a supplement to compromise.js NER.
 */

export const GAZETTEER_ORGS = [
  // ── International organizations ──────────────────────────────────────────
  { name: 'United Nations', aliases: ['UN', 'U.N.'], type: 'international' },
  { name: 'NATO', aliases: ['North Atlantic Treaty Organization'], type: 'military_alliance' },
  { name: 'European Union', aliases: ['EU', 'E.U.'], type: 'international' },
  { name: 'World Health Organization', aliases: ['WHO'], type: 'international' },
  { name: 'International Criminal Court', aliases: ['ICC'], type: 'international' },
  { name: 'UNHCR', aliases: ['UN Refugee Agency', 'United Nations High Commissioner for Refugees'], type: 'humanitarian' },
  { name: 'World Food Programme', aliases: ['WFP'], type: 'humanitarian' },
  { name: 'International Committee of the Red Cross', aliases: ['ICRC', 'Red Cross'], type: 'humanitarian' },
  { name: 'International Monetary Fund', aliases: ['IMF'], type: 'financial' },
  { name: 'World Bank', aliases: ['WBG', 'World Bank Group'], type: 'financial' },
  { name: 'Organization for Security and Co-operation in Europe', aliases: ['OSCE'], type: 'international' },
  { name: 'African Union', aliases: ['AU', 'A.U.'], type: 'international' },
  { name: 'Association of Southeast Asian Nations', aliases: ['ASEAN'], type: 'international' },
  { name: 'Economic Community of West African States', aliases: ['ECOWAS'], type: 'international' },
  { name: 'Arab League', aliases: ['League of Arab States', 'LAS'], type: 'international' },
  { name: 'International Atomic Energy Agency', aliases: ['IAEA'], type: 'international' },
  { name: 'Organisation for the Prohibition of Chemical Weapons', aliases: ['OPCW'], type: 'international' },
  { name: 'BRICS', aliases: ['BRICS+', 'Brazil Russia India China South Africa'], type: 'international' },
  { name: 'G7', aliases: ['Group of Seven'], type: 'international' },
  { name: 'G20', aliases: ['Group of Twenty'], type: 'international' },
  { name: 'Shanghai Cooperation Organisation', aliases: ['SCO'], type: 'international' },
  { name: 'Collective Security Treaty Organization', aliases: ['CSTO'], type: 'military_alliance' },
  { name: 'Organisation for Economic Co-operation and Development', aliases: ['OECD'], type: 'international' },
  { name: 'World Trade Organization', aliases: ['WTO'], type: 'international' },
  { name: 'UNESCO', aliases: ['United Nations Educational Scientific and Cultural Organization'], type: 'international' },

  // ── Regional bodies & economic blocs ──────────────────────────────────────
  { name: 'Southern African Development Community', aliases: ['SADC'], type: 'international' },
  { name: 'East African Community', aliases: ['EAC'], type: 'international' },
  { name: 'Intergovernmental Authority on Development', aliases: ['IGAD'], type: 'international' },
  { name: 'Common Market for Eastern and Southern Africa', aliases: ['COMESA'], type: 'international' },
  { name: 'Economic Community of Central African States', aliases: ['ECCAS', 'CEEAC'], type: 'international' },
  { name: 'Community of Sahel-Saharan States', aliases: ['CEN-SAD', 'CENSAD'], type: 'international' },
  { name: 'Mercosur', aliases: ['MERCOSUR', 'Mercado Común del Sur', 'Southern Common Market'], type: 'international' },
  { name: 'Caribbean Community', aliases: ['CARICOM'], type: 'international' },
  { name: 'Pacific Islands Forum', aliases: ['PIF', 'South Pacific Forum'], type: 'international' },
  { name: 'Gulf Cooperation Council', aliases: ['GCC'], type: 'international' },
  { name: 'Organization of American States', aliases: ['OAS', 'OEA'], type: 'international' },
  { name: 'Commonwealth of Independent States', aliases: ['CIS'], type: 'international' },
  { name: 'Eurasian Economic Union', aliases: ['EAEU', 'EEU', 'EurAsEC'], type: 'international' },
  { name: 'Organisation of Islamic Cooperation', aliases: ['OIC', 'Organization of Islamic Cooperation'], type: 'international' },
  { name: 'Andean Community', aliases: ['CAN', 'Comunidad Andina'], type: 'international' },
  { name: 'Central American Integration System', aliases: ['SICA', 'Sistema de la Integración Centroamericana'], type: 'international' },
  { name: 'Union of South American Nations', aliases: ['UNASUR', 'UNASUL'], type: 'international' },
  { name: 'Community of Latin American and Caribbean States', aliases: ['CELAC'], type: 'international' },
  { name: 'Mano River Union', aliases: ['MRU'], type: 'international' },
  { name: 'Indian Ocean Rim Association', aliases: ['IORA'], type: 'international' },
  { name: 'South Asian Association for Regional Cooperation', aliases: ['SAARC'], type: 'international' },
  { name: 'Melanesian Spearhead Group', aliases: ['MSG'], type: 'international' },
  { name: 'Visegrád Group', aliases: ['V4', 'Visegrad Group', 'Visegrad Four'], type: 'international' },
  { name: 'Nordic Council', aliases: ['Nordic Council of Ministers'], type: 'international' },
  { name: 'African Development Bank', aliases: ['AfDB', 'ADB Africa'], type: 'financial' },
  { name: 'Asian Development Bank', aliases: ['ADB'], type: 'financial' },
  { name: 'Inter-American Development Bank', aliases: ['IDB', 'IADB'], type: 'financial' },
  { name: 'New Development Bank', aliases: ['NDB', 'BRICS Bank'], type: 'financial' },
  { name: 'Asian Infrastructure Investment Bank', aliases: ['AIIB'], type: 'financial' },
  { name: 'European Central Bank', aliases: ['ECB'], type: 'financial' },

  // ── UN specialized agencies & bodies ─────────────────────────────────────
  { name: 'UNICEF', aliases: ['United Nations Children\'s Fund', 'UN Children\'s Fund'], type: 'humanitarian' },
  { name: 'UNDP', aliases: ['United Nations Development Programme'], type: 'international' },
  { name: 'Food and Agriculture Organization', aliases: ['FAO'], type: 'international' },
  { name: 'International Labour Organization', aliases: ['ILO'], type: 'international' },
  { name: 'International Court of Justice', aliases: ['ICJ', 'World Court'], type: 'international' },
  { name: 'UN Security Council', aliases: ['UNSC', 'Security Council'], type: 'international' },
  { name: 'UN General Assembly', aliases: ['UNGA', 'General Assembly'], type: 'international' },
  { name: 'UN Human Rights Council', aliases: ['UNHRC', 'HRC'], type: 'international' },
  { name: 'International Organization for Migration', aliases: ['IOM'], type: 'humanitarian' },
  { name: 'UN Environment Programme', aliases: ['UNEP'], type: 'international' },
  { name: 'UN Women', aliases: ['United Nations Entity for Gender Equality'], type: 'international' },
  { name: 'UN Peacekeeping', aliases: ['DPKO', 'Blue Helmets', 'UN peacekeepers'], type: 'military' },
  { name: 'International Telecommunication Union', aliases: ['ITU'], type: 'international' },
  { name: 'World Meteorological Organization', aliases: ['WMO'], type: 'international' },

  // ── Military / paramilitary groups ───────────────────────────────────────
  { name: 'Wagner Group', aliases: ['Africa Corps', 'PMC Wagner', 'Wagner PMC', 'Afrika Korps'], type: 'paramilitary' },
  { name: 'Hezbollah', aliases: ['Hizballah', 'Hizbullah', 'Party of God', 'Lebanese Hezbollah'], type: 'paramilitary' },
  { name: 'Hamas', aliases: ['Islamic Resistance Movement', 'Harakat al-Muqawama al-Islamiyya'], type: 'militant' },
  { name: 'Houthis', aliases: ['Ansar Allah', 'Ansarallah', 'Houthi movement', 'Houthi rebels'], type: 'rebel' },
  { name: 'Taliban', aliases: ['Islamic Emirate of Afghanistan', 'IEA'], type: 'militant' },
  { name: 'Al-Shabaab', aliases: ['Harakat al-Shabaab al-Mujahideen', 'HSM', 'Al Shabaab'], type: 'terrorist' },
  { name: 'ISIS', aliases: ['ISIL', 'Daesh', 'Islamic State', 'IS', 'Da\'esh', 'Islamic State of Iraq and Syria', 'Islamic State of Iraq and the Levant'], type: 'terrorist' },
  { name: 'Boko Haram', aliases: ['ISWAP', 'Islamic State West Africa Province', 'Jamaat Ahl as-Sunnah lid-Dawah wal-Jihad'], type: 'terrorist' },
  { name: 'PKK', aliases: ['Kurdistan Workers Party', 'Partiya Karkerên Kurdistanê'], type: 'rebel' },
  { name: 'FARC', aliases: ['FARC-EP', 'Revolutionary Armed Forces of Colombia', 'Fuerzas Armadas Revolucionarias de Colombia', 'Estado Mayor Central'], type: 'rebel' },
  { name: 'ELN', aliases: ['National Liberation Army', 'Ejército de Liberación Nacional'], type: 'rebel' },
  { name: 'Rapid Support Forces', aliases: ['RSF', 'Janjaweed militias'], type: 'paramilitary' },
  { name: 'Sudanese Armed Forces', aliases: ['SAF', 'Sudan Armed Forces'], type: 'military' },
  { name: 'Syrian Democratic Forces', aliases: ['SDF', 'Quwwat Suriya al-Dimuqratiyya'], type: 'military' },
  { name: 'YPG', aliases: ["People's Protection Units", 'Yekîneyên Parastina Gel'], type: 'military' },
  { name: 'Libyan National Army', aliases: ['LNA', 'Libyan Arab Armed Forces', 'LAAF'], type: 'military' },
  { name: 'Government of National Accord', aliases: ['GNA', 'GNU', 'Government of National Unity Libya'], type: 'military' },
  { name: 'Azov Brigade', aliases: ['Azov Battalion', 'Azov Regiment', 'National Corps'], type: 'military' },
  { name: 'Al-Qaeda', aliases: ['AQ', 'Al Qaeda', 'Al Qaida', 'Qa\'idat al-Jihad'], type: 'terrorist' },
  { name: 'Hayat Tahrir al-Sham', aliases: ['HTS', 'Al-Nusra Front', 'Jabhat al-Nusra', 'Jabhat Fateh al-Sham'], type: 'militant' },
  { name: "Kata'ib Hezbollah", aliases: ['KH', 'Hezbollah Brigades', 'Kataib Hezbollah'], type: 'paramilitary' },
  { name: 'Popular Mobilization Forces', aliases: ['PMF', 'PMU', 'Hashd al-Shaabi', 'Al-Hashd al-Shaabi'], type: 'paramilitary' },
  { name: 'Islamic Revolutionary Guard Corps', aliases: ['IRGC', 'Sepah', 'Pasdaran', 'IRGC-QF', 'Quds Force'], type: 'military' },
  { name: 'Interahamwe', aliases: [], type: 'paramilitary' },
  { name: 'M23', aliases: ['March 23 Movement', 'Mouvement du 23 Mars', 'CNDP'], type: 'rebel' },
  { name: 'FDLR', aliases: ['Democratic Forces for the Liberation of Rwanda', 'Forces Démocratiques de Libération du Rwanda'], type: 'rebel' },
  { name: 'Allied Democratic Forces', aliases: ['ADF', 'ADF-NALU'], type: 'terrorist' },
  { name: 'AQIM', aliases: ['Al-Qaeda in the Islamic Maghreb', 'Al-Qaida in the Lands of the Islamic Maghreb'], type: 'terrorist' },
  { name: 'JNIM', aliases: ['Jama\'at Nusrat al-Islam wal-Muslimin', 'Group for the Support of Islam and Muslims'], type: 'terrorist' },
  { name: 'Janjaweed', aliases: ['Janjawid'], type: 'paramilitary' },
  { name: 'Peshmerga', aliases: ['Kurdish Peshmerga', 'KRG forces'], type: 'military' },
  { name: 'Free Syrian Army', aliases: ['FSA', 'Syrian National Army', 'SNA Syria'], type: 'rebel' },
  { name: 'Tiger Forces', aliases: ['25th Special Mission Forces Division', 'Quwwat al-Nimr'], type: 'military' },
  { name: 'Somali National Army', aliases: ['SNA', 'Somali Federal Army'], type: 'military' },
  { name: 'AMISOM', aliases: ['ATMIS', 'African Union Mission in Somalia', 'African Union Transition Mission in Somalia'], type: 'military' },
  { name: 'Tigray People\'s Liberation Front', aliases: ['TPLF'], type: 'rebel' },
  { name: 'Oromo Liberation Army', aliases: ['OLA', 'OLF-Shane', 'Oromo Liberation Front'], type: 'rebel' },
  { name: 'Tehrik-i-Taliban Pakistan', aliases: ['TTP', 'Pakistani Taliban', 'Tehrik-e-Taliban'], type: 'terrorist' },
  { name: 'Balochistan Liberation Army', aliases: ['BLA'], type: 'rebel' },
  { name: 'Kachin Independence Army', aliases: ['KIA', 'Kachin Independence Organisation', 'KIO'], type: 'rebel' },
  { name: 'Arakan Army', aliases: ['AA', 'United League of Arakan'], type: 'rebel' },
  { name: 'Karen National Union', aliases: ['KNU', 'Karen National Liberation Army', 'KNLA'], type: 'rebel' },
  { name: 'Ta\'ang National Liberation Army', aliases: ['TNLA', 'Palaung Liberation Army'], type: 'rebel' },
  { name: 'Myanmar National Democratic Alliance Army', aliases: ['MNDAA', 'Kokang Army'], type: 'rebel' },
  { name: 'National Unity Government', aliases: ['NUG Myanmar', 'NUG'], type: 'rebel' },
  { name: 'People\'s Defence Force', aliases: ['PDF Myanmar', 'PDF'], type: 'rebel' },
  { name: 'New People\'s Army', aliases: ['NPA', 'CPP-NPA'], type: 'rebel' },
  { name: 'Abu Sayyaf', aliases: ['Abu Sayyaf Group', 'ASG'], type: 'terrorist' },
  { name: 'Bangsamoro Islamic Freedom Fighters', aliases: ['BIFF'], type: 'terrorist' },
  { name: 'Naxalites', aliases: ['CPI-Maoist', 'Communist Party of India Maoist', 'Naxal'], type: 'rebel' },
  { name: 'United Wa State Army', aliases: ['UWSA', 'Wa State Army'], type: 'rebel' },
  { name: 'Lord\'s Resistance Army', aliases: ['LRA', 'LRA Uganda'], type: 'rebel' },
  { name: 'Al-Mourabitoun', aliases: ['Al Mourabitoun', 'The Sentinels'], type: 'terrorist' },
  { name: 'Ansarul Islam', aliases: ['Ansaroul Islam', 'Ansar ul Islam'], type: 'terrorist' },
  { name: 'Islamic State in the Greater Sahara', aliases: ['ISGS', 'IS Sahara'], type: 'terrorist' },
  { name: 'Macina Liberation Front', aliases: ['FLM', 'Katiba Macina'], type: 'terrorist' },
  { name: 'RENAMO', aliases: ['Resistência Nacional Moçambicana', 'Mozambican National Resistance'], type: 'rebel' },
  { name: 'ADF-NALU', aliases: ['National Army for the Liberation of Uganda'], type: 'rebel' },
  { name: 'Séléka', aliases: ['Seleka', 'Séléka coalition'], type: 'rebel' },
  { name: 'Anti-balaka', aliases: ['Anti-Balaka', 'Antibalaka'], type: 'paramilitary' },
  { name: 'Fuerzas Armadas Revolucionarias de Colombia', aliases: ['FARC dissidents', 'FARC-EMC', 'Segunda Marquetalia'], type: 'rebel' },
  { name: 'Clan del Golfo', aliases: ['Gulf Clan', 'Autodefensas Gaitanistas', 'AGC'], type: 'paramilitary' },
  { name: 'Sendero Luminoso', aliases: ['Shining Path', 'SL'], type: 'rebel' },
  { name: 'Tren de Aragua', aliases: ['TdA'], type: 'criminal' },
  { name: 'Primeiro Comando da Capital', aliases: ['PCC'], type: 'criminal' },
  { name: 'Jalisco New Generation Cartel', aliases: ['CJNG', 'Cartel Jalisco Nueva Generación'], type: 'criminal' },
  { name: 'Sinaloa Cartel', aliases: ['CDS', 'Cartel de Sinaloa'], type: 'criminal' },

  // ── Peacekeeping & multinational missions ────────────────────────────────
  { name: 'MONUSCO', aliases: ['UN Mission in Congo', 'United Nations Organization Stabilization Mission in the DRC'], type: 'military' },
  { name: 'MINUSMA', aliases: ['UN Mission in Mali', 'United Nations Multidimensional Integrated Stabilization Mission in Mali'], type: 'military' },
  { name: 'UNMISS', aliases: ['UN Mission in South Sudan', 'United Nations Mission in South Sudan'], type: 'military' },
  { name: 'UNIFIL', aliases: ['UN Interim Force in Lebanon', 'United Nations Interim Force in Lebanon'], type: 'military' },
  { name: 'MINUSCA', aliases: ['UN Mission in Central African Republic'], type: 'military' },
  { name: 'Multinational Joint Task Force', aliases: ['MNJTF', 'Lake Chad MNJTF'], type: 'military' },
  { name: 'G5 Sahel Joint Force', aliases: ['G5 Sahel', 'FC-G5S'], type: 'military' },

  // ── NGOs / humanitarian organizations ────────────────────────────────────
  { name: 'Amnesty International', aliases: ['AI', 'Amnesty'], type: 'ngo' },
  { name: 'Human Rights Watch', aliases: ['HRW'], type: 'ngo' },
  { name: 'Médecins Sans Frontières', aliases: ['MSF', 'Doctors Without Borders', 'Medecins Sans Frontieres'], type: 'humanitarian' },
  { name: 'Reporters Without Borders', aliases: ['RSF', 'Reporters Sans Frontières', 'RSF media'], type: 'ngo' },
  { name: 'UN Office for the Coordination of Humanitarian Affairs', aliases: ['OCHA'], type: 'humanitarian' },
  { name: 'Save the Children', aliases: [], type: 'humanitarian' },
  { name: 'Oxfam', aliases: ['Oxfam International'], type: 'humanitarian' },
  { name: 'CARE International', aliases: ['CARE'], type: 'humanitarian' },
  { name: 'International Rescue Committee', aliases: ['IRC'], type: 'humanitarian' },
  { name: 'Norwegian Refugee Council', aliases: ['NRC'], type: 'humanitarian' },
  { name: 'Red Crescent', aliases: ['IFRC', 'International Federation of Red Cross and Red Crescent Societies'], type: 'humanitarian' },
  { name: 'UNRWA', aliases: ['United Nations Relief and Works Agency', 'UN Relief and Works Agency for Palestine Refugees'], type: 'humanitarian' },
  { name: 'Médecins du Monde', aliases: ['MdM', 'Doctors of the World'], type: 'humanitarian' },
  { name: 'Action Against Hunger', aliases: ['ACF', 'Action Contre la Faim'], type: 'humanitarian' },
  { name: 'Humanity & Inclusion', aliases: ['HI', 'Handicap International'], type: 'humanitarian' },

  // ── News agencies ─────────────────────────────────────────────────────────
  { name: 'Reuters', aliases: ['Thomson Reuters'], type: 'news_agency' },
  { name: 'Associated Press', aliases: ['AP'], type: 'news_agency' },
  { name: 'Agence France-Presse', aliases: ['AFP'], type: 'news_agency' },
  { name: 'Xinhua', aliases: ['Xinhua News Agency', 'New China News Agency'], type: 'news_agency' },
  { name: 'TASS', aliases: ['TASS Russian News Agency'], type: 'news_agency' },
  { name: 'Al Jazeera', aliases: ['AJE', 'Al-Jazeera', 'Al Jazeera English', 'Al Jazeera Arabic'], type: 'news_agency' },
  { name: 'BBC', aliases: ['BBC News', 'British Broadcasting Corporation'], type: 'news_agency' },
  { name: 'Radio France Internationale', aliases: ['RFI'], type: 'news_agency' },
  { name: 'Deutsche Welle', aliases: ['DW'], type: 'news_agency' },
  { name: 'France 24', aliases: ['France24'], type: 'news_agency' },
];

export const GAZETTEER_ROLES = [
  { pattern: /\bpresident\b/i, type: 'leader' },
  { pattern: /\bprime\s+minister\b/i, type: 'leader' },
  { pattern: /\bchancellor\b/i, type: 'leader' },
  { pattern: /\b(king|queen|emir|sultan|monarch)\b/i, type: 'leader' },
  { pattern: /\bminister\s+of\s+(defense|defence)\b/i, type: 'official' },
  { pattern: /\bdefense\s+minister\b/i, type: 'official' },
  { pattern: /\bdefence\s+minister\b/i, type: 'official' },
  { pattern: /\bminister\s+of\s+foreign\s+affairs\b/i, type: 'official' },
  { pattern: /\bforeign\s+minister\b/i, type: 'official' },
  { pattern: /\bminister\s+of\s+(the\s+)?interior\b/i, type: 'official' },
  { pattern: /\bsecretary\s+of\s+state\b/i, type: 'official' },
  { pattern: /\bsecretary[\s-]general\b/i, type: 'official' },
  { pattern: /\b(general|commander|commander[\s-]in[\s-]chief|chief\s+of\s+(staff|defense))\b/i, type: 'military' },
  { pattern: /\bambassador\b/i, type: 'diplomat' },
  { pattern: /\bspecial\s+(envoy|representative)\b/i, type: 'diplomat' },
];
