import React, { useCallback, useEffect, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { Link } from 'react-router-dom';
import { Sparkles, Copy, RefreshCcw, AlertTriangle } from 'lucide-react';
import useSubscriptionStore from '../stores/subscriptionStore';
import { fetchEventBrief, generateEventBrief } from '../services/backendService.js';

function briefToMarkdown(brief) {
  if (!brief) return '';
  const actors = (brief.actors || [])
    .map((a) => `- **${a.name}**${a.role ? ` — ${a.role}` : ''}`)
    .join('\n');
  const cites = (brief.citations || [])
    .map((c) => `[${c.index}] ${c.source}${c.url ? ` — ${c.url}` : ''}`)
    .join('\n');
  return `# ${brief.lede || ''}

${brief.summary || ''}

## Key actors
${actors || '_None listed._'}

## Suggested angle
${brief.angle || ''}

## Citations
${cites || '_No citations available._'}

---
Generated by Mapr · model: \`${brief.modelUsed || 'unknown'}\` · ${brief.generatedAt || ''}
`;
}

function relative(iso) {
  if (!iso) return '';
  const ts = Date.parse(iso);
  if (!Number.isFinite(ts)) return '';
  const m = Math.floor((Date.now() - ts) / 60000);
  if (m < 1) return 'just now';
  if (m < 60) return `${m}m ago`;
  const h = Math.floor(m / 60);
  if (h < 24) return `${h}h ago`;
  return `${Math.floor(h / 24)}d ago`;
}

export default function BriefGenerator({ event } = {}) {
  const { t } = useTranslation();
  const isAuthenticated = useSubscriptionStore((s) => s.isAuthenticated);
  const [brief, setBrief] = useState(null);
  const [cached, setCached] = useState(false);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState(null);
  const [errorCode, setErrorCode] = useState(null);
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    if (!event?.id) return;
    let cancelled = false;
    fetchEventBrief(event.id)
      .then((res) => {
        if (cancelled) return;
        setBrief(res?.brief || null);
        setCached(Boolean(res?.brief));
      })
      .catch(() => { /* silently — no cache yet */ });
    return () => { cancelled = true; };
  }, [event?.id]);

  const handleGenerate = useCallback(async ({ force = false } = {}) => {
    if (!event?.id) return;
    setBusy(true);
    setError(null);
    setErrorCode(null);
    try {
      const res = await generateEventBrief(event.id, { force });
      setBrief(res.brief);
      setCached(Boolean(res.cached));
    } catch (err) {
      setError(err.message || t('brief.errorGeneric'));
      setErrorCode(err.code || err.payload?.code || null);
    } finally {
      setBusy(false);
    }
  }, [event?.id, t]);

  const handleCopy = useCallback(async () => {
    if (!brief) return;
    try {
      await navigator.clipboard.writeText(briefToMarkdown(brief));
      setCopied(true);
      setTimeout(() => setCopied(false), 1500);
    } catch { /* clipboard unavailable */ }
  }, [brief]);

  if (!event?.id) return null;

  return (
    <section className="event-detail-section brief-section" data-testid="brief-generator">
      <header className="brief-head">
        <h2 className="event-detail-section-title brief-title">
          <Sparkles size={12} aria-hidden /> {t('brief.title')}
        </h2>
        <div className="brief-actions">
          {brief && (
            <button type="button" className="btn brief-copy-btn" onClick={handleCopy} title={t('brief.copyMarkdown')}>
              <Copy size={11} aria-hidden /> {copied ? t('brief.copied') : t('brief.copyMarkdown')}
            </button>
          )}
          {isAuthenticated && (
            <button
              type="button"
              className="btn primary brief-generate-btn"
              onClick={() => handleGenerate({ force: Boolean(brief) })}
              disabled={busy}
              data-testid="brief-generate-btn"
            >
              {brief ? <RefreshCcw size={11} aria-hidden /> : <Sparkles size={11} aria-hidden />}
              <span>
                {busy
                  ? t('brief.generating')
                  : brief
                    ? t('brief.regenerate')
                    : t('brief.generate')}
              </span>
            </button>
          )}
        </div>
      </header>

      {!isAuthenticated && (
        <div className="brief-empty mono">
          {t('brief.loginRequired')} <Link to="/account" className="brief-signin-link">{t('auth.signIn')}</Link>
        </div>
      )}

      {error && (
        <div
          className={`brief-error${errorCode === 'AI_NOT_CONFIGURED' ? ' brief-error--soft' : ''}`}
          role="alert"
          data-testid="brief-error"
        >
          <AlertTriangle size={12} aria-hidden />
          <span>{errorCode === 'AI_NOT_CONFIGURED' ? t('brief.notConfigured') : error}</span>
        </div>
      )}

      {brief && (
        <article className="brief-body" data-testid="brief-body">
          <p className="brief-lede">{brief.lede}</p>
          <div className="brief-summary">
            {(brief.summary || '').split(/\n\n+/).map((p, i) => <p key={i}>{p}</p>)}
          </div>
          {Array.isArray(brief.actors) && brief.actors.length > 0 && (
            <div className="brief-actors">
              <div className="micro">{t('brief.actors')}</div>
              <ul>
                {brief.actors.map((a, i) => (
                  <li key={`${a.name}-${i}`}><b>{a.name}</b>{a.role ? ` — ${a.role}` : ''}</li>
                ))}
              </ul>
            </div>
          )}
          {brief.angle && (
            <div className="brief-angle">
              <div className="micro">{t('brief.angle')}</div>
              <p>{brief.angle}</p>
            </div>
          )}
          {Array.isArray(brief.citations) && brief.citations.length > 0 && (
            <div className="brief-citations">
              <div className="micro">{t('brief.citations')}</div>
              <ol>
                {brief.citations.map((c) => (
                  <li key={`cite-${c.index}`} value={c.index}>
                    {c.url
                      ? <a href={c.url} target="_blank" rel="noreferrer noopener">{c.source}</a>
                      : c.source}
                  </li>
                ))}
              </ol>
            </div>
          )}
          <footer className="brief-footer mono micro">
            {brief.modelUsed && <span>{t('brief.modelLabel')}: {brief.modelUsed}</span>}
            {brief.generatedAt && <span>· {t('brief.cachedAt', { relative: relative(brief.generatedAt) })}</span>}
            {cached && <span>· cache</span>}
          </footer>
        </article>
      )}
    </section>
  );
}
