/**
 * briefingMarkdown.js — generates a markdown briefing report from events.
 *
 * Produces a downloadable .md file with:
 *  - Header with timestamp and filter summary
 *  - Summary statistics
 *  - Event table with title, severity, region, source count
 *  - Grouped events by severity tier
 */

const SEVERITY_TIERS = [
  { label: 'Critical', min: 85 },
  { label: 'Elevated', min: 60 },
  { label: 'Watch', min: 30 },
  { label: 'Low', min: 0 },
];

/**
 * Returns a human-readable severity label for a numeric score.
 * @param {number} severity
 * @returns {string}
 */
function severityLabel(severity) {
  if (severity >= 85) return 'Critical';
  if (severity >= 60) return 'Elevated';
  if (severity >= 30) return 'Watch';
  return 'Low';
}

/**
 * Formats a date string or timestamp into a readable format.
 * @param {string|number|undefined} dateVal
 * @returns {string}
 */
function formatDate(dateVal) {
  if (!dateVal) return '—';
  try {
    const d = new Date(dateVal);
    return d.toISOString().replace('T', ' ').slice(0, 16) + ' UTC';
  } catch {
    return '—';
  }
}

/**
 * Generates markdown text summarizing the given events.
 *
 * @param {object[]} events – array of canonical event objects
 * @param {object}   filters – active filter configuration
 * @returns {string} markdown content
 */
export function generateBriefingMarkdown(events = [], filters = {}) {
  const now = new Date();
  const lines = [];

  // ── Header ──
  lines.push('# Mapr Intelligence Briefing');
  lines.push('');
  lines.push(`**Generated:** ${now.toISOString().replace('T', ' ').slice(0, 19)} UTC`);
  lines.push(`**Events:** ${events.length}`);
  lines.push('');

  // ── Filter summary ──
  const filterParts = [];
  if (filters.dateWindow) filterParts.push(`Time window: ${filters.dateWindow}`);
  if (filters.minSeverity > 0) filterParts.push(`Min severity: ${filters.minSeverity}`);
  if (filters.minConfidence > 0) filterParts.push(`Min confidence: ${filters.minConfidence}%`);
  if (filters.sortMode && filters.sortMode !== 'severity') filterParts.push(`Sort: ${filters.sortMode}`);
  if (filterParts.length > 0) {
    lines.push('**Filters:** ' + filterParts.join(' · '));
    lines.push('');
  }

  // ── Summary statistics ──
  const regions = new Set();
  let totalSources = 0;
  const severityCounts = { Critical: 0, Elevated: 0, Watch: 0, Low: 0 };
  const lifecycleCounts = {};

  for (const event of events) {
    if (event.region) regions.add(event.region);
    if (event.isoA2) regions.add(event.isoA2);
    totalSources += event.articleCount || 1;
    const label = severityLabel(event.severity || 0);
    severityCounts[label] = (severityCounts[label] || 0) + 1;
    if (event.lifecycle) {
      lifecycleCounts[event.lifecycle] = (lifecycleCounts[event.lifecycle] || 0) + 1;
    }
  }

  lines.push('## Summary');
  lines.push('');
  lines.push(`| Metric | Value |`);
  lines.push(`| ------ | ----- |`);
  lines.push(`| Total events | ${events.length} |`);
  lines.push(`| Regions covered | ${regions.size} |`);
  lines.push(`| Total source articles | ${totalSources} |`);
  lines.push(`| Critical | ${severityCounts.Critical} |`);
  lines.push(`| Elevated | ${severityCounts.Elevated} |`);
  lines.push(`| Watch | ${severityCounts.Watch} |`);
  lines.push(`| Low | ${severityCounts.Low} |`);
  lines.push('');

  // ── Events by severity tier ──
  for (const tier of SEVERITY_TIERS) {
    const tierEvents = events.filter((e) => {
      const s = e.severity || 0;
      const label = severityLabel(s);
      return label === tier.label;
    });
    if (tierEvents.length === 0) continue;

    lines.push(`## ${tier.label} Events (${tierEvents.length})`);
    lines.push('');
    lines.push('| # | Title | Severity | Region | Sources | First Seen |');
    lines.push('| - | ----- | -------- | ------ | ------- | ---------- |');

    tierEvents.forEach((event, idx) => {
      const title = (event.title || 'Untitled').replace(/\|/g, '\\|');
      const region = (event.region || event.locality || event.isoA2 || '—').replace(/\|/g, '\\|');
      const sources = event.articleCount || 1;
      const firstSeen = formatDate(event.firstSeenAt);
      lines.push(`| ${idx + 1} | ${title} | ${event.severity || 0} | ${region} | ${sources} | ${firstSeen} |`);
    });

    lines.push('');
  }

  // ── Footer ──
  lines.push('---');
  lines.push('');
  lines.push('*Generated by [Mapr OSINT Platform](https://github.com/tor/mapr)*');
  lines.push('');

  return lines.join('\n');
}
